import fs from 'fs'
let c = fs.readFileSync('src/app/(dashboard)/surveys/page.tsx', 'utf8')
c = c.replace(/formatDual\("So'rovnomalar',/g, 'formatDual("So\'rovnomalar",')
c = c.replace(/formatDual\("Yangi so'rovnoma yaratish',/g, 'formatDual("Yangi so\'rovnoma yaratish",')
c = c.replace(/formatDual\("So'rovnoma nomi',/g, 'formatDual("So\'rovnoma nomi",')
c = c.replace(/formatDual\("Bo'sh qoldirsangiz/g, 'formatDual("Bo\'sh qoldirsangiz')
c = c.replace(/formatDual\("Standart GREEN PROCESSING savollarini qo'shish \(11 ta savol\)',/g, 'formatDual("Standart GREEN PROCESSING savollarini qo\'shish (11 ta savol)",')
c = c.replace(/formatDual\("Hali so'rovnoma yo'q',/g, 'formatDual("Hali so\'rovnoma yo\'q",')
c = c.replace(/formatDual\("Yuqoridagi tugmani bosib yangi so'rovnoma yarating',/g, 'formatDual("Yuqoridagi tugmani bosib yangi so\'rovnoma yarating",')
c = c.replace(/'Hali javob yo\\'q'/g, `"Hali javob yo'q"`)
c = c.replace(/'Noma\\'lum restoran'/g, `"Noma'lum restoran"`)
fs.writeFileSync('src/app/(dashboard)/surveys/page.tsx', c)
